spring:
   profiles: dev  #开发环境
   application:
    name: mySpringCloud-provider-dev
    
---

spring:
   profiles: test  #测试环境
   application:
    name: mySpringCloud-provider-test
    
---

spring:
   profiles: pro  #生产环境
   application:
    name: mySpringCloud-provider-pro 